# Generated by Django 3.0.2 on 2020-01-25 14:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import posts.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Accom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=200)),
                ('province', models.CharField(blank=True, max_length=200)),
                ('lng', models.FloatField(blank=True)),
                ('lat', models.FloatField(blank=True)),
                ('type', models.SlugField(blank=True)),
                ('gender', models.SlugField(default='Mixed')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=70)),
                ('price', models.IntegerField(default=0)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('electricity', models.BooleanField(default=True)),
                ('shuttle', models.BooleanField(default=False)),
                ('wifi', models.BooleanField(default=False)),
                ('furnished', models.BooleanField(default=False)),
                ('cover', models.CharField(blank=True, max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(blank=True, max_length=200)),
                ('direction', models.BooleanField(default=None)),
                ('accom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.Accom')),
                ('viewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=posts.models.upload_location)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='posts.Accom')),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.SlugField(default='pending')),
                ('accom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.Accom')),
                ('viewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
