# Generated by Django 3.0.2 on 2020-01-25 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20200125_1439'),
    ]

    operations = [
        migrations.DeleteModel(
            name='internalMessage',
        ),
    ]
