# Generated by Django 3.0.2 on 2020-01-25 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
