# Generated by Django 2.2.6 on 2020-01-26 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_internalmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accom',
            name='description',
            field=models.CharField(max_length=140),
        ),
    ]
